ALTER TABLE "Screen" ADD COLUMN "createdById" TEXT;
ALTER TABLE "Media" ADD COLUMN "createdById" TEXT;
ALTER TABLE "Layout" ADD COLUMN "createdById" TEXT;
ALTER TABLE "Playlist" ADD COLUMN "createdById" TEXT;
ALTER TABLE "Screen" ADD CONSTRAINT "Screen_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Media" ADD CONSTRAINT "Media_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Layout" ADD CONSTRAINT "Layout_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Playlist" ADD CONSTRAINT "Playlist_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
